name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: target
